myapp/core/views.py
from flask import render_template, redirect, url_for, Blueprint, flash, request
from myapp import db
from myapp.models import DailyPlan, Worker, Schedule, Date, SchedulePayment, Payments
from .forms import PaymentsF
import datetime as dt

core = Blueprint("core", __name__)

@core.route("/", methods = ["GET", "POST"])
def index():
    ''' Current date evaluation '''
    current_date = dt.date.today()
    # date = current_date.strftime("%A, %d %B %Y"), 
    ''' Workers, schedules, dates number and last item's date evaluation '''
    workers = db.session.execute(db.Select(Worker).order_by(Worker.id)).scalars().all()
    # worker_id_list = [worker.id for worker in workers]
    schedules = db.session.execute(db.Select(Schedule).order_by(Schedule.id)).scalars().all()
    # schedules_id_list = [schedule.id for schedule in schedules]
    any_worker = len(workers)
    any_schedule = len(schedules)
    form = PaymentsF(any_worker, any_schedule)
    if request.method == "GET":
        if (any_schedule and any_worker):
            for i in range(any_worker):
                for j in range(any_schedule):
                    pay = db.session.execute(db.Select(SchedulePayment.pay).where(db.and_(SchedulePayment.worker == workers[i], SchedulePayment.schedule == schedules[j]))).scalar()
                    if pay:
                        form.field[i].payment[j].payment.data = pay
                    else:
                        form.field[i].payment[j].payment.data = 0
        else:
            form = None
        schedule_count = []
        for worker in workers:
            schedule_count_list = []
            for schedule in schedules:
                cnt = DailyPlan.query.filter(db.and_(DailyPlan.worker == worker, DailyPlan.schedule == schedule)).count()
                schedule_count_list.append(cnt)
            schedule_count.append({worker.name: schedule_count_list})
        any_date = len(db.session.execute(db.Select(Date).order_by(Date.id)).scalars().all())
        last_year = db.session.execute(db.Select(Date).order_by(Date.id.desc())).scalar()
        ''' Dates controls '''
        ''' Is any date present in DB? Which year the date refers to? '''
        if (not any_date):
            flash("Maybe this is your first run... There aren't any defined dates. Please, wait.", category = "red")
            return redirect(url_for("dates.create_dates", date = current_date.year))
        elif (any_date and current_date.year > last_year.year):
            flash("A year has passed... Please, wait for the adjournment of the database.", category = "red")
            return redirect(url_for("dates.create_dates", date = current_date.year))
        if (not any_worker):
            flash("Hmm... It seems you have no workers to manage...", category = "yellow")
        if (not any_schedule):
            flash("Hmm... It seems you have not defined any schedule...", category = "yellow")
        return render_template("index.html", num_worker = any_worker, schedules = schedules, any_schedule = any_schedule, schedule_count = schedule_count, form = form)   
    
    if request.method == "POST":
        # workers_post = db.session.execute(db.Select(Worker).order_by(Worker.id)).scalars().all()
        # schedules_post = db.session.execute(db.Select(Schedule).order_by(Schedule.id)).scalars().all()
        for i in range(len(workers)):
            workers[i].credit = 0.0
            for j in range(len(schedules)):
                pay = form.field[i].payment[j].payment.data
                #verifica se ci sono turni per questo lavoratore ancora da pagare e quanti
                turni_da_riaggiornare = DailyPlan.query.filter(db.and_(DailyPlan.worker == workers[i], DailyPlan.schedule == schedules[j], DailyPlan.has_been_paid == False)).count()
                already = db.session.execute(db.Select(SchedulePayment).where(db.and_(SchedulePayment.worker == workers[i], SchedulePayment.schedule == schedules[j]))).scalar()
                if already and already == pay:
                    pass
                elif already and not (already == pay):
                    already.pay = pay
                else:
                    new_pay = SchedulePayment(schedule_id = schedules[j].id, worker_id = workers[i].id, pay = pay)
                    db.session.add(new_pay)
                workers[i].credit = workers[i].credit + turni_da_riaggiornare*pay
            db.session.commit()
        return redirect(url_for("core.index"))       

@core.route("/payments-list")
def payments_list():
    payments = db.session.execute(db.Select(Payments).order_by(Payments.id.desc())).scalars().all()
    return render_template("payments_list.html", list = payments)

@core.route("/info")
def info():
    ''' Info page '''
    return render_template("info.html")

myapp/dates/views.py
from flask import Blueprint, redirect, render_template, flash, url_for, request
import datetime as dt
from myapp import db
from myapp.models import Worker, Schedule, Date, DailyPlan, SchedulePayment
from myapp.dates.forms import AddSchedule, DynamicSchedule

dates = Blueprint("dates", __name__)

@dates.route("/dates/add/<date>")
def create_dates(date):
    ''' Creates dates for the current year '''
    end_date = dt.date(int(date), 12, 31).toordinal()
    for i in range(dt.date(int(date), 1, 1).toordinal(), end_date + 1):
        new_date = dt.date.fromordinal(i)
        date_obj = Date(fulldate = new_date)
        db.session.add(date_obj)
        db.session.commit()
    flash("A full-year date plan has been created successfully for you!", category = "green")
    return redirect(url_for("core.index"))

@dates.route("/schedule/add", methods = ["GET", "POST"])
def create_schedule():
    '''Creates a new schedule (name and hours)'''
    form = AddSchedule()
    if form.validate_on_submit():
        new_schedule = Schedule(name = form.name.data, hours = form.hours.data)
        db.session.add(new_schedule)
        db.session.commit()
        flash("A new schedule has been created successfully!", category = "green")
        return redirect(url_for("core.index"))
    return render_template("schedule_create.html", form = form)

@dates.route("/schedule/<int:id>", methods = ["GET", "POST"])
def schedule_update(id):
    '''Updates a selected schedule'''
    schedule = Schedule.query.get_or_404(id)
    form = AddSchedule()
    if form.validate_on_submit():
        schedule.name = form.name.data
        schedule.hours = form.hours.data
        db.session.commit()
        flash(f"Schedule {schedule.name} has been successfully updated!", category = "green")
        return redirect(url_for("core.index"))
    elif request.method == "GET":
        form.name.data = schedule.name
        form.hours.data = schedule.hours
    return render_template("schedule_create.html", form = form)

@dates.route("/schedule/list")
def list():
    '''Selects all schedules for their rendering'''
    schedule_list = Schedule.query.all()
    return render_template("schedule_list.html", list = schedule_list)

@dates.route("/schedule/delete/<int:id>")
def delete_schedule(id):
    '''Deletes the selected schedule (and all rows in DailyPlan containing it)'''
    schedule = Schedule.query.get_or_404(id)
    workers = db.session.execute(db.Select(Worker).order_by(Worker.id)).scalars().all()
    for worker in workers:
        turni_da_riaggiornare = DailyPlan.query.filter(db.and_(DailyPlan.worker == worker, DailyPlan.schedule == schedule, DailyPlan.has_been_paid == False)).count()
        pay = db.session.execute(db.Select(SchedulePayment.pay).where(db.and_(SchedulePayment.worker == worker, SchedulePayment.schedule == schedule))).scalar()
        try:
            worker.credit = worker.credit - turni_da_riaggiornare*pay
        except TypeError:
            pass
    db.session.delete(schedule)
    db.session.commit()
    flash(f'Schedule "{schedule.name}" ({schedule.hours} hours) has been successfully deleted!', category = "green")
    return redirect(url_for("core.index"))

@dates.route("/plan")
def a_plan():
    year = dt.date.today().year
    return redirect(url_for("dates.plan", year = year))

@dates.route("/plan/<int:year>")
def plan(year):
    page = request.args.get("page", 1, type = int)
    dates = db.session.execute(db.Select(Date).where(db.and_(Date.year == year, Date.month_number == page))).scalars().all()
    #finquiok
    all_workers = db.session.execute(db.Select(Worker).order_by(Worker.id)).scalars().all()
    all_workers_name = [worker.name for worker in all_workers]
    if not dates:
        return render_template("404.html")
    else:
        month_num = str(page)
        datetime_object = dt.datetime.strptime(month_num, "%m")
        full_month_name = datetime_object.strftime("%B")
        scheds = {}
        for worker in all_workers:
            scheds[worker.name] = []
            for d in dates:
                sched_id =  db.session.execute(db.Select(DailyPlan.schedule_id).where(db.and_(DailyPlan.date_id == d.id, DailyPlan.worker_id == worker.id))).scalar()
                if sched_id:
                    sched_name = db.session.execute(db.Select(Schedule).where(Schedule.id == sched_id)).scalar()

                    scheds[worker.name].append(str(sched_name.name))
                else:
                    scheds[worker.name].append("")
        return render_template("plan.html", dates = dates, month = full_month_name, year = year, workers = all_workers, scheds = scheds)

@dates.route("/plan/day/<int:id>", methods = ["GET", "POST"])
def manage_day(id):
    # lista nomi e id lavoratori
    workers = db.session.execute(db.Select(Worker).order_by(Worker.id)).scalars().all()
    current_date = db.session.execute(db.Select(Date).where(Date.id == id)).scalar()
    workers_names = [w.name for w in workers]
    workers_ids = [w.id for w in workers]
    n_workers = len(workers_names)
    # lista di turni
    schedules_name = db.session.execute(db.Select(Schedule.name).order_by(Schedule.id)).scalars().all()
    # renderizzo il form e associo i nomi dei lavoratori agli StringField e i loro id ai SelectField
    form = DynamicSchedule(n_workers, schedules_name)
    for i in range(n_workers):
        form.work_sche[i].worker.data = workers_names[i]
        form.work_sche[i].schedule.id = workers_ids[i]
    if request.method == "GET":
            for item in form.work_sche:
                sch = db.session.execute(db.Select(DailyPlan.schedule_id).where(db.and_(DailyPlan.date_id == id, DailyPlan.worker_id == item.schedule.id))).scalar()
                shift_name = db.session.execute(db.Select(Schedule.name).where(Schedule.id == sch)).scalar()
                item.schedule.data = shift_name

    if request.method == "POST":
        for item in form.work_sche:
            value = item.form.schedule.data
            current_worker = db.session.execute(db.Select(Worker).where(Worker.id == item.form.schedule.id)).scalar()
            selected_schedule = (db.session.execute(db.Select(Schedule).where(Schedule.name == str(value))).scalar())
            # È NECESSARIO PRIMA VERIFICARE SE I DATI C'ERANO GIÀ
            already_present = db.session.execute(db.Select(DailyPlan).where(db.and_(DailyPlan.date == current_date, DailyPlan.worker == current_worker))).scalar()
            if (already_present):
                # # ---- aggiornare il credito del dipendente, a meno che non sia stato già pagato questo turno
                # if (not already_present.has_been_paid):
                #     old_payment = db.session.execute(db.Select(SchedulePayment.pay).where(db.and_(SchedulePayment.worker_id == current_worker, SchedulePayment.schedule_id == already_present.schedule_id))).scalar()
                # # CERCARE LA TARIFFA DI QUESTO TURNO (se c'è)
                # if payment := db.session.execute(db.Select(SchedulePayment.pay).where(db.and_(SchedulePayment.schedule_id == selected_schedule, SchedulePayment.worker_id == current_worker))).scalar():
                #     pass
                # # DECURTARE DAL CREDITO E SOMMARE IL NUOVO IMPORTO
                already_present.schedule_id = str(selected_schedule.id)
            else:
                # aggiornare il credito del dipendente
                #
                new_plan = DailyPlan(date_id = current_date.id, worker_id = current_worker.id, schedule_id = selected_schedule.id)
                db.session.add(new_plan)
            db.session.commit()
        return redirect(url_for("dates.a_plan"))

    return render_template("plan_daily.html", form = form, sche = schedules_name, string = workers_names)

myapp/workers/views.py
from myapp import db
from sqlalchemy import func
from datetime import date
from myapp.models import Worker, DailyPlan, SchedulePayment, Date, Payments
from myapp.workers.forms import AddWorker, UpdateWorker, PaymentFunc
from myapp.workers.picture_handler import add_profile_pic
from flask import render_template, redirect, url_for, Blueprint, flash, request

users = Blueprint("users", __name__)

@users.route("/worker/register", methods = ["GET", "POST"])
def register():
    '''Allows the registration of a new worker'''
    form = AddWorker()
    if form.validate_on_submit():
        new_worker = Worker(name = form.name.data,
                            surname = form.surname.data,
                            role = form.role.data,
                            phone = form.phone.data,
                            email = form.email.data)
        db.session.add(new_worker)
        db.session.commit()
        flash(f"Worker {new_worker.name} has been successfully registered!", category = "green")
        return redirect(url_for("core.index"))
    return render_template("register.html", form = form)

@users.route("/worker/<int:id>", methods = ["GET", "POST"])
def account(id):
    '''Updates the selected worker'''
    worker = Worker.query.get_or_404(id)
    form = UpdateWorker()
    if form.validate_on_submit():
        if form.picture.data:
            worker_name = worker.name
            pic = add_profile_pic(form.picture.data, worker_name)
            worker.profile_image = pic
        worker.name = form.name.data
        worker.surname = form.surname.data
        worker.role = form.role.data
        worker.phone = form.phone.data
        worker.email = form.email.data
        db.session.commit()
        flash(f"Worker {worker.name} has been successfully updated!", category = "green")
        return redirect(url_for("core.index"))
    elif request.method == "GET":
        form.name.data = worker.name
        form.surname.data = worker.surname
        form.role.data = worker.role
        form.phone.data = worker.phone
        form.email.data = worker.email
    return render_template("profile.html", form = form)

@users.route("/worker/list")
def list():
    workers_list = Worker.query.all()
    return render_template("list.html", list = workers_list)

@users.route("/worker/delete/<int:id>")
def delete(id):
    worker = Worker.query.get_or_404(id)
    db.session.delete(worker)
    db.session.commit()
    flash(f"Worker {worker.name} has been successfully deleted!", category = "green")
    return redirect(url_for("core.index"))

@users.route("/worker/<int:id>/payment/<int:month>/<int:year>", methods = ["GET", "POST"])
def manage_payment(id, month, year):
    # RECUPERA IL LAVORATORE DAL DATABASE
    monthly_pay = 0.0
    worker = db.session.execute(db.Select(Worker).where(Worker.id == id)).scalar()
    # STIMA LO STIPENDIO PER IL MESE CORRENTE, TENENDO PRESENTE CHE PUÒ ESSERCI STATO UN ACCONTO
    dates = db.session.execute(db.Select(Date.id).filter(db.and_(Date.month_number == month, Date.year == year))).scalars().all()
    plans = db.session.execute(db.Select(DailyPlan).filter(db.and_(DailyPlan.worker == worker, DailyPlan.has_been_paid == False))).scalars().all()
    plans_worked = [plan.schedule_id for plan in plans if plan.date_id in dates]
    for i in plans_worked:
        sum_pays = db.session.query(func.sum(SchedulePayment.pay)).filter(db.and_(SchedulePayment.worker_id == worker.id, SchedulePayment.schedule_id == i)).scalar()
        try:
            monthly_pay = monthly_pay + sum_pays
        except TypeError:
            pass
    form = PaymentFunc(monthly_pay)
    if request.method == "POST":
        if form.validate_on_submit():
            if monthly_pay == 0.0:
                # se non c'è niente da pagare, reindirizza con messaggio
                flash(f"No credit to pay for {worker.name}!", category = "yellow")
                return redirect(url_for("core.index"))
            # ridurre il credito del lavoratore e cambiare lo status dei turni in PAGATO (true)

            worker.credit = worker.credit - monthly_pay
            for plan in plans:
                plan.has_been_paid = True
            new_transaction = Payments(type = "Monthly pay", quantity = monthly_pay, date_id = date.today(), worker_id = worker.id)
            db.session.add(new_transaction)
            db.session.commit()
            flash(f"Transaction correctly executed for {worker.name}!", category = "green")
            return redirect(url_for("core.index"))
    return render_template("payment_manage.html", form = form)
      

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Urbanist:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="icon" type="image/png" href={{ url_for('static', filename='calendar-icon.png') }}>
    <link rel="stylesheet" href={{ url_for('static', filename='styles.css') }}>
    <title>WorkManager</title>
  </head>
  <body>
    <div class="container">
    {% include "header.html" %}

    {% block content %}{% endblock %}
    </div>
</body>
</html>

myapp/templates/header.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <div class="align-center">
            <img class="bi me-2" width="40" height="40" src={{ url_for("static", filename = "logo.png")}} />
            <span class="fs-4">Work Manager</span>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item"><a href={{  url_for('core.index')  }} class="nav-link active" aria-current="page">Home</a></li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="" data-bs-toggle="dropdown" aria-expanded="false">Workers</a>
                    <menu class="dropdown-menu">
                      <li><a class="dropdown-item" href={{ url_for("users.register") }}>Register</a></li>
                      <li><a class="dropdown-item" href={{ url_for("users.list") }}>List</a></li>
                    </menu>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="" data-bs-toggle="dropdown" aria-expanded="false">Schedules</a>
                    <menu class="dropdown-menu">
                      <li><a class="dropdown-item" href={{ url_for("dates.create_schedule") }}>Create</a></li>
                      <li><a class="dropdown-item" href={{ url_for("dates.list") }}>List</a></li>
                    </menu>
                </li>
                <li class="nav-item"><a href={{ url_for("dates.a_plan") }} class="nav-link">Plan</a></li>
                <li class="nav-item"><a href={{ url_for("core.payments_list") }} class="nav-link">Payments History</a></li>
                <li class="nav-item"><a href={{ url_for("core.info") }} class="nav-link">Info</a></li>
                  </ul>
        </div>
    </div>
  </nav>

myapp/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="container justify-content-center align-items-center">

  {% with yellows = get_flashed_messages(category_filter=["yellow"]) %}
    {% if yellows %}
      {% for msg in yellows %}
        <section class="container alert alert-warning" role="alert">
          {{ msg }}
        </section>
      {% endfor %}
    {% endif %}
  {% endwith %}

  {% with greens = get_flashed_messages(category_filter=["green"]) %}
    {% if greens %}
      {% for msg in greens %}
        <section class="alert alert-success" role="alert">
          {{ msg }}
        </section>
      {% endfor %}
    {% endif %}
  {% endwith %}

  <section class="alert alert-info" role="alert">
    You have {{ num_worker }} workers to manage.
    {% if num_worker %}
      You can update or remove workers anytime (Psst: <a href={{ url_for("users.list") }}>here</a>'s a shortcut for you!).
    {% endif %}
  </section>

  {% if schedule_count and schedules %}
  <section id="index-page" class="container d-flex flex-wrap justify-content-space-around align-items-flex-start">

    <article class="index-table col-xl-6">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col"></th>
            {% for schedule in schedules %}
                  <th class="schedule-item" scope="col"><span>{{ schedule.name }}</span></th>
            {% endfor %}
          </tr>
        </thead>
        <tbody>
          {% for dict in schedule_count %}
            {% for item in dict %}
              <tr>
                <th scope="row">{{ item }}</th>
                {% for values in dict.values() %}
                  {% for i in values %}
                    <td class="value-item">{{i}}</td>
                  {% endfor %}
                {% endfor %}
              </tr>
            {% endfor %}
          {% endfor %}
        </tbody>
      </table>
    </article>
    {% if form %}
    <article class="form-table col-xl-6">
      <form class="container cont-payments" method="POST">
        {{ form.hidden_tag() }}
        <table class="table">
          <thead>
            <tr>
              <th scope="col"></th>
              {% for schedule in schedules %}
                    <th class="schedule-item" scope="col"><span>{{ schedule.name }}</span></th>
              {% endfor %}
            </tr>
          </thead>

          <tbody>
            {% for i in range(num_worker) %}
              <tr>
                <th scope="row"></th>
                {% for j in range(any_schedule) %}
                  <td class="value-item">{{ form.field[i].payment[j].payment(class="input-payment") }}</td>
                {% endfor %}
              </tr>
            {% endfor %}
          </tbody>
        </table>
        {{ form.submit(class="btn btn-primary commit") }}
      </form>
    </article>
    {% endif %}
  </section>
{% endif %}
{% endblock %}

myapp/templates/list.html
{% extends "base.html" %}

{% block content %}
{% if list %}

  <section class="workers-page container d-flex flex-wrap align-items-flex-start">
    {% for worker in list %}
    <div class="card col-3">
      <img align="center" src="{{ url_for('static', filename = 'profile_pics/' + worker.profile_image) }}" class="card-img-top"/>
      <div class="card-body-title">
        <h4 class="card-title">{{ worker.name }} <br> {{ worker.surname }}</h4>
      </div>
      <menu class="list-group list-group-flush">
        {% if worker.role %}
          <li class="list-group-item"><span>Role</span>: {{ worker.role }}</li>
        {% else %}
          <li class="list-group-item"><span>Role</span>: not available</li>
          {% endif %}
        {% if worker.credit == 0.0 %}
          <li class="list-group-item"><span>Credit</span>:<span style="color:red"> {{ worker.credit }} $</span></li>
        {% else %}
          <li class="list-group-item"><span>Credit</span>:<span style="color:green"> {{ worker.credit }} $</span></li>
        
        {% endif %}
        {% if worker.phone %}
          <li class="list-group-item"><span>Phone</span>: {{ worker.phone }}</li>
        {% else %}
          <li class="list-group-item"><span>Phone</span>: not available</li>
        {% endif %}
        {% if worker.email %}
          <li class="list-group-item"><address><a href="mailto:{{ worker.email }}">{{ worker.email }}</a></address></li>
        {% else %}
          <li class="list-group-item"><span>Email</span>: not available</li>
        {% endif %}
      </menu>
      <div class="card-body-btn d-flex justify-content-center">
        <a href={{ url_for("users.account", id = worker.id) }} class="btn btn-info">Update</a>
        <a href={{ url_for("users.delete", id = worker.id) }} class="btn btn-danger">Delete</a>
      </div>

    </div>

    {% endfor %}

  </section>

  {% else %}
  <div class="container d-flex justify-content-center align-items-center">
    <div class="container alert alert-warning" role="alert">
      There are no workers in the list.
    </div>
  </div>
{% endif %}




{% endblock %}

myapp/templates/payment_detail.html
<article class="payment-detail col-6">
    <div class="card">
        <div class="card-body">
            <h3>{{ payment.date_id }}</h3>
            <br>
            <p>{{ payment.worker.name }} has received a {{ payment.type }} of {{ payment.quantity }}$.</p>
        </div>
      </div>
</article>

myapp/templates/payment_manage.html
{% extends "base.html" %}

{% block content %}
<div class="container payment-preform d-flex align-items-center flex-column">
    <h2>Please, commit the payment...</h2>
    <form id="payment-form" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-floating mb-3">
    {{ form.value(class="form-control") }}
    </div>
    {{ form.submit(class="btn btn-primary") }}
    </form>
</div>



{% endblock %}

myapp/templates/plan.html
{% extends "base.html" %}

{% block content %}
<section class="container d-flex flex-column align-items-center">
  <div class="month-year-date">
    <h2>{{month}}, {{year}}</h2>
  </div>
</section>

<section class="container d-flex flex-column align-items-center">
  <div class="table">
    <table class="table">
      <thead>
        <tr>
          <th scope="col"></th>
          {% for date in dates %}
              {% if date.is_red %}
                <th class="date-item" scope="col" style="width:5px; height:3px;"><a href="{{url_for('dates.manage_day', id = date.id)}}" class="red-item"><span>{{ date.fulldate.day }}{{ date.day_of_week[0] }}</span></a></th>
              {% else %}
                <th class="date-item" scope="col" style="width:5px; height:3px;"><a href="{{url_for('dates.manage_day', id = date.id)}}" class="normal-item"><span>{{ date.fulldate.day }}{{  date.day_of_week[0]  }}</span></a></th>
              {% endif %}
          {% endfor %}
        </tr>
      </thead>

      <tbody>
        {% for worker in workers %}
          <tr>
            <th scope="row"><a href="{{url_for('users.manage_payment', id = worker.id, month=dates[0].month_number, year = dates[0].year)}}">{{ worker.name }}</a></th>
            {% for sch in scheds[worker.name] %}
              <td>{{sch}}</td>
            {% endfor %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</section>

<nav aria-label="Plan pages">
  <ul class="pagination justify-content-center">
  {% for i in range(1,13) %}
    {% if i == month %}
      <li class="page-item disabled">
        <a class="page-link" href="{{ url_for('dates.plan', year = year, page = i) }}">{{ i }}</a>
      </li>
    {% else %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('dates.plan', year = year, page = i) }}">{{ i }}</a>
      </li>
    {% endif %}
  {% endfor %}
</nav>

{% endblock %}

myapp/templates/schedule_list.html
{% extends "base.html" %}

{% block content %}
{% if list %}

  <section class="schedules-page container d-flex flex-wrap align-items-flex-start">
    {% for schedule in list %}
    <div class="card col-3">
      <svg align="center" xmlns="http://www.w3.org/2000/svg" height=80 weight=80 fill="currentColor" class="card-img-top bi bi-clock" viewBox="0 0 16 16">
        <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71z"/>
        <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16m7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0"/>
      </svg>      
      <div class="card-body-title">
        <h4 class="card-title">{{ schedule.name }}</h4>
      </div>
      <menu class="list-group list-group-flush">
        <li class="list-group-item"><span>Hours</span>: {{  schedule.hours  }}</li>
      </menu>
      <div class="card-body-btn d-flex justify-content-center">
        <a href={{ url_for("dates.schedule_update", id = schedule.id) }} class="btn btn-info">Update</a>
        <a href={{ url_for("dates.delete_schedule", id = schedule.id) }} class="btn btn-danger">Delete</a>
      </div>
    </div>
  {% endfor %}
  </section>

  {% else %}

  <div class="container d-flex justify-content-center align-items-center">
    <div class="container alert alert-warning" role="alert">
      There are no schedules in the list.
    </div>
  </div>
{% endif %}




{% endblock %}